# Generated by Django 5.1.6 on 2025-02-21 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Price',
            fields=[
                ('item_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('item_name', models.TextField()),
                ('price', models.IntegerField()),
            ],
        ),
    ]
