# Generated by Django 5.1.4 on 2025-02-14 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('subject', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('q_no', models.IntegerField()),
                ('question', models.CharField(max_length=200)),
            ],
        ),
    ]
