# Generated by Django 5.1.6 on 2025-02-10 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRUD_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='price',
            field=models.FloatField(),
        ),
    ]
