# Generated by Django 5.1.6 on 2025-02-21 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locate_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='location_id',
        ),
        migrations.AlterField(
            model_name='location',
            name='pincode',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
