# Generated by Django 5.1.6 on 2025-02-21 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locate_app', '0002_remove_location_location_id_alter_location_pincode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='pincode',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
