# Generated by Django 5.1.6 on 2025-02-11 06:12

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('user', models.CharField(max_length=100, verbose_name=django.contrib.auth.models.User)),
                ('e_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('emp_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('doj', models.DateField()),
                ('password', models.CharField(max_length=100)),
            ],
        ),
    ]
