# Generated by Django 5.1.4 on 2025-02-14 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('pr_Id', models.IntegerField(primary_key=True, serialize=False)),
                ('pr_Name', models.CharField(max_length=200)),
                ('price', models.FloatField()),
                ('qty', models.IntegerField()),
                ('dop', models.DateField()),
            ],
        ),
    ]
