# Generated by Django 5.1.6 on 2025-02-12 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('st_Id', models.IntegerField(primary_key=True, serialize=False)),
                ('stock_Name', models.CharField(max_length=200)),
                ('price', models.FloatField()),
                ('qty', models.IntegerField()),
                ('date_of_purchase', models.DateField()),
            ],
        ),
    ]
