# Generated by Django 5.1.6 on 2025-02-21 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('trip_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('trip_duration', models.TextField()),
                ('trip_date', models.DateField()),
                ('trip_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('no_of_passengers', models.IntegerField()),
                ('boarding', models.TextField()),
                ('destination', models.TextField()),
            ],
        ),
    ]
