# Generated by Django 5.1.6 on 2025-02-14 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('movie_Id', models.IntegerField(primary_key=True, serialize=False)),
                ('movie_Name', models.CharField(max_length=200)),
                ('rating', models.FloatField()),
                ('genre', models.CharField(max_length=100)),
            ],
        ),
    ]
